zuul:
  ignoredServices: '*'
  debug:
    request: false
  prefix: /api
  routes:
    persons:
      path: /persons/**
      serviceId: person-service
    files:
      path: /files/**
      serviceId: file-service
    monitoring:
      path: /monitoring/**
      serviceId: person-ingest-service
      
spring:
  http:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
