info:
  app:
    name: ${spring.application.name}

management:
  security:
    enabled: false

security:
  basic:
    enabled: false
    
spring:
  http:
    multipart:
      max-request-size: 100MB
      max-file-size: 100MB
