cloud:
  aws:
    credentials:
      accessKey: 1DPTE3KBQ9WFIVEG7IRW
      secretKey: sAJfYrZN43kjJkTN6vGUzv8KZaSPUTNDMkaEzQ6e
      endpoint: http://177.184.18.105:8080/

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: ngcloud
          contentType: application/json
    rabbit:
      bindings:
        output:
          producer:
            routingKeyExpression: "'upload-person'"
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
