spring:
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
    jpa:
      hibernate:
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

liquibase:
    contexts: cloud
    drop-first: true
