spring:
  jackson:
    date-format: java.text.SimpleDateFormat
    default-property-inclusion: non_empty
  cloud:
    stream:
      bindings:
        input:
          destination: persons
      rabbit:
        bindings:
          input:
            consumer:
              bindingRoutingKey: person-service

server:
  compression:
    enabled: true
    mime-types: application/json
    min-response-size: 1
  display-name: Person Service

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

liquibase:
  change-log: classpath:/db/changelog/db.changelog-master.xml