spring:
  cloud:
    stream:
      bindings:
        output:
          destination: persons # exchange
          contentType: application/json #
        input:
          destination: ngcloud # exchange
          group: "person-ingest.queue" # queue
      rabbit:
        bindings:
          input:
            consumer:
              bindingRoutingKey: upload-person
          output:
            producer:
              routingKeyExpression: "'person-service'"
  http:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: java.text.SimpleDateFormat
    default-property-inclusion: non_empty
